### ISSUE TITLE
Extend and finish automated benchmark scripts

### ISSUE THREAD

**Issue by sahib** [sahib/rmlint#131]
_Benchmark scripts are at:_

```
tests/test_speed/*
```

**Current State**
- `benchmark.py` builds and installs all competitors in `/tmp`. 
- Every software is run x times with flushed caches and one additional time with
  flushed caches. The software is run on generated or real datasets.
- A `benchmark.json` file is written containing all relevant measurements.
- `plot_benchmark.py` creates a nice svg bar plot out of the json file.

**Done:**
- Move install scripts into separate bash scripts.

**ToDo:**
- Write docs/benchmark.rst -- done.
- Generate some more realistic datasets. Especially some datasets where rmlint
  shines (directory trees on different disks e.g.).
- Provide baseline timing (time it takes to read all found duplicates from
  disk).
- Extract the number of files the tool found. If numbers are not matching up
  give a warning.
- Write a merge script that combines several `benchmark.json` files and plots 
  a line plot on how every tool performed on each individual dataset.

**Comment by sahib** [comment]
Mostly done. What's new:

- Both ``benchmark.py`` and ``plot_benchmark.py`` understand a rich set of options.
- Installation scripts are (dumb) little bash scripts now.
- Added a baseline program (a simple python dupe finder) that servers as slowest competitor.
- Parse number of found dupes and sets for each program (numbers tend to not match well up between tools).
- Peak memory usage is also included, but not for each run.
- Plot by timing, cpu usage and dupes found.
- Results are written to timestamped directories to avoid confusion.

Sample usage:

```bash
$ sudo python benchmark.py -r -d /usr -d /tmp -p dupd  # produces directory with json files.
$ python plot_benchmark.py bench-output-2015-09-14T22:12:55+0200 # produces dir with svgs.
$ chromium plot-output-2015-09-14T22:12:55+0200/*.svg
```

``sudo`` is still needed in order to flush the filesystem cache.

**Comment by sahib** [comment]
Here are some first "results": 

http://rmlint.readthedocs.org/en/latest/benchmarks.html

It's not perfect yet, but it shows the direction. Click on the images for tooltips and hover effects.

**Comment by 0ion9** [comment]
Looking at the results page, I think that rmlint-spooky is getting the wrong color. In the graph, there is a dark grey bar where I would expect spooky to show, but in the legend it is shown as an orangeish color very similar to baseline.py

**Comment by SeeSpotRun** [comment]
Personally I think the runs apart from the first are pretty meaningless.  In the real world, the user should only need to run the tool once, and it's unlikely that many of the files are cached before they start.

Tests such as http://www.virkki.com/jyri/articles/index.php/duplicate-file-detection-performance/ are pretty meaningless ("first I ran it once and ignored the time, just to populate file caches").  With that said, dupd is impressively fast on cached comparisons.

Rmlint's file reading strategy deliberately doesn't try to read 2 files from the same disk at the same time, in order to reduce disk seeks / thrash.  I think this probably penalises rmlint on runs where file data is already cached.

**Comment by sahib** [comment]
@0ion9: Yup, that seems to be a rendering bug in ``pygal``, it works fine with the default style applied.

@SeeSpotRun: That's exactly what missing. Some text that explains the results. But for that one might need the full picture, even if it's just there to say "As you can see...". 

It should be also noted that ``rmlint`` is capable of using ``--replay`` in the second run and up, which makes re-running mostly neglectable.

A slightly weird result is also that ``-a spooky`` is not really useful, but that might be partly due my amd64 cpu. But using another cheap hashfunction for ``-PP`` might be a good idea.

**Comment by SeeSpotRun** [comment]
https://github.com/SeeSpotRun/rmlint/commit/a40f970560a78303e258f0b70a4d51724c4768ea should give a bit of a speedup.  I had a sort() call in there which was supposed to ensure the hasher gets the least busy hashing thread, but it turns out the sort time was costing more than the gain.

**Comment by sahib** [comment]
Cool, that chopped off a few seconds on the re-runs.
New plots will follow in a few days, will collect some other changes first.

**Comment by sahib** [comment]
I added some text to explain some aspects of the plots. 
Maybe someone can validate it, it was late and beer was involved

**Comment by SeeSpotRun** [comment]
I've started building a synthetic set of test files to help reconcile the number of duplicates found.  By having 1/2/4/8/16 etc sets of duplicates of different types we can quickly infer what each duplicate finder is/isn't finding.  I'm trying to cover all the thinks that a duplicate finder might miss (intentionally or due to a bug) as well as potential false positives:
- [x] Files >4GB (max 32 bit unsigned int)
- [x] Files >2GB (max 32 bit signed int)
- [x] Bind-mounts such that the same file appears under two paths (but is not a duplicate)
- [x] Hidden files
- [x] Files in hidden folders
- [x] Symlinked files
- [x] Files in symlinked folders
- [x] Hardlinked files
- [ ] Files that you have to cross a filesystem boundary to reach
- [ ] Files with weird characters in their name
- [ ] "Normal" files

**Comment by sahib** [comment]
- Files with spaces, tabs, newlines, simple quotes, double quotes and commas (you know why :smirk:) in them (@ weird names).
- Files with only 1 byte that are different (off by one errors).

Will you provide a set of sh files to generate those datasets? (some may be harder like filesystem boundaries)

**Comment by SeeSpotRun** [comment]
No sh files, just some ugly python: https://github.com/SeeSpotRun/rmlint/blob/synth-bench-dataset/tests/test_speed/benchmark.py#L534
