### ISSUE TITLE
2.11 TODO

### ISSUE THREAD

**Issue by SeeSpotRun** [sahib/rmlint#510]
Probably won't get back to this for couple of weeks so making myself a list...

- [ ] Add set -e to bash script #469 
- [ ] Add blake3 checksum #424 ([WIP](https://github.com/SeeSpotRun/rmlint/tree/blake3_local))
    - [ ] Set blake3 as default checksum
- [ ] Clarify behaviour of `--no-hardlinked` #495
- [ ] Add option to keep reflinks #328 ([WIP](https://github.com/SeeSpotRun/rmlint/tree/feature/keep_reflinked))
- [ ] Reduce memory footprint of RmFile
- [ ] Update docs
- [ ] Update changelog
- [ ] Bump version

Post-release packaging:
- [ ] MacPort publish Portfile
- [ ] homebrew recipe update
- [ ] Other distros

Future roadmap:
* Develop gui workflow
* Localisation of gui #488
* Similar-dirs identification / report
* Btrfs dedupe workflow #338 #349
* Autocomplete #251 
* Update benchmarking #324

**Comment by RayOei** [comment]
I noticed new commits to `master` after the `2.10.3` release.
Isn't it better to try to get `develop` up and running again (merge `master`) and work from there towards a new version?
Either way, it will be helpful to bump the `.version` at this point, I think?

**Comment by vassilit** [comment]
> I noticed new commits to `master` after the `2.10.3` release. Isn't it better to try to get `develop` up and running again (merge `master`) and work from there towards a new version? 

Yes

> Either way, it will be helpful to bump the `.version` at this point, I think?


I think we should get rid of a committed .version file and use `git describe` in scripts.

**Comment by vassilit** [comment]
https://github.com/sahib/rmlint/milestone/7
